import React, { useState } from "react";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import { useSelector } from "react-redux";
import Head from 'next/head'
import { CloseCircleOutlined } from "@ant-design/icons";


const Description = ({ setshowdescription, id }:any) => {
  const items = useSelector((state:any) => state.allcarts.items);
  const singleitem = items.filter((elm:any) => {
    elm.id === id;
    return elm.id === id;
  })[0];
  console.log("singleitem", singleitem);
  if (!singleitem) {
    return null; 
  }
  return (
    <>
     <Head>
        <title>Description Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </Head>
      <style>
        {`
   .overlay {
    position: fixed;
      margin-right:auto;
      margin-left:auto;
      width: 100%;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: rgba(0, 0, 0, 0.7);
      z-index: 9999;
   
    }
    .animation{
      animation: fade 0.3s;
    
    }
    @keyframes fade {
      from {
        opacity: 0;
        transform: scale(0.8);
      }
      to {
        opacity: 1;
        transform: scale(1);
      }
    }
    .desc img{
        border-radius:50px;
    }
    p{
      color:black;
      font-size:16px;
    }
    .x-mark{
      float:right;
      font-size:30px;
    
      color:black;
   
      
    }
    
  
 
 
   
   
   
   
   
   `}
      </style>

      <div className="overlay">
        <Box
          sx={{
            height: "auto",
            width: "44%",
            backgroundColor: "white",
            borderRadius: 12,
            padding: 6,
          }}
          className="animation"
        >
          <CloseCircleOutlined  onClick={()=>setshowdescription(false)} className="x-mark"/>
       
          <div className="desc">
            <img src={singleitem.img} alt="" height="350" width="600" style={{marginLeft:"auto",marginRight:"auto"}}/>
            <h4>
              <b>Name:</b>
            </h4>
            <p>{singleitem.title}</p>
            <h4>
              <b>Screen size:</b>
            </h4>
            <p>{singleitem.size}</p>
            <h4>
              <b>Features</b>
            </h4>
            <p>{singleitem.full}</p>
          </div><br />
          <Button
            variant="contained"
            onClick={() => {
              setshowdescription(false);
            }}
          >
            Close
          </Button>
        </Box>
      </div>
    </>
  );
};

export default Description;
