// Next imports
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from 'next/head'
// Components imports
import Navbar1 from "../Components/Navbar1";
// Antd imports
import { Button, Result } from 'antd';


const error = () => {
  const router=useRouter();
  const[second,setseconds]=useState<number>(10);


  

  useEffect(()=>{
    const interval=setInterval(()=>{
      setseconds((prevsecond)=>prevsecond - 1)
    },1000)
    return  ()=> clearInterval(interval)
  },[]);
  
  useEffect(()=>{
    if(second===0){
     
      router.push("/Landing")
         
      
    }
  },[second])
  const handlehome = () =>{
    router.push("/Landing")
  }
    // const router=useRouter()
   
    // useEffect(()=>{
    //   setTimeout(() => {
    //     router.push("/")
    //   }, 3000);
    // },[]);
  
  return (

    <div>
       <Head>
        <title>Error Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <style>
        {`

   
    .back{
        padding:12px;
        color:white;
        background-color:black;
        font-weight:700;
        border-radius:50px;
        width:120px;
        margin-left:740px;
        

    }
   
    
    
    
    
    
    `}
      </style>
    
      {/* <div className="image">
        <Image
          src="https://github.githubassets.com/images/modules/notifications/inbox-zero.svg"
          alt=""
          height={400}
          width={450}
          priority={true}
        
         className="img"/>
        
      </div>
     
      <h2 style={{textAlign:"center",color:"red"}}>404 Error !!!</h2>
     <Link href="/allpost"> <button className="back" >Back to Home
</button></Link> */}
   <Result
    status="404"
    title="404"
    subTitle="Sorry, the page you visited does not exist."
    extra={<Button type="primary" onClick={handlehome}>Back Home</Button>}
  />
<h4 style={{textAlign:"center",color:"green"}} >Redirecting to Home page in {second} seconds</h4>


    </div>
  );
};

export default error;


// https://ouch-cdn2.icons8.com/fgJKMaVTkdnsgrRX516Zcuib9wOWMHQWsdgrJBOzm4s/rs:fit:477:456/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvMTQy/L2I4MjEyNGIyLTM2/OGItNDcwMy1hY2U3/LWMyOTc0YTk2OGI3/Mi5wbmc.png