"use client";
// Next imports
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from 'next/head'
// MUI imports
import {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
} from "@mui/material";
// Redux imports
import { useDispatch, useSelector } from "react-redux";
import { deleteuser, readuser } from "../Features/register";
import { AppDispatch, RootState } from "../store";
// Styles imports
import edit from "../styles/edit.module.css";
import styles from "../styles/delete.module.css";
import prompt from "../styles/prompt.module.css";
// Components imports
import Navbar1 from "../Components/Navbar1";
import Loader from "../Components/Loader";
import Update1 from "../Components/Update1";



const allregister = () => {
  const router = useRouter();
  const dispatch: AppDispatch = useDispatch();
  const [showdelete, setshowdelete] = useState<boolean>(false);
  const [showupdate, setshowupdate] = useState<boolean>(false);
  const [id, setId] = useState<number>();
  const[username, setusername] = useState<string>();

  const { rusers, isloading } = useSelector(
    (state:RootState) => state.grand
  );
  useEffect(() => {
    dispatch(readuser());
    console.log("read users are", rusers);
  }, []);

  const handledelete = (userId:number,username:string) => {
    setshowdelete(true);
    setId(userId);
    setusername(username)
  };
  const confirmhandledelete = () => {
    dispatch(deleteuser(id)).then(()=>{
      dispatch(readuser());
      setshowdelete(false);
    })
  };
  
  if (isloading) {
    return <Loader />;
  }
  const goback = () => {
    router.back();
  };
  return (
    <>
     <Head>
        <title>Registered Users Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      />
      {showdelete && (
        <div className={prompt.modal}>
          <div className={prompt.modalContent}>
            <p>Are you sure you want to delete "{username}" ?</p>
            <div className={prompt.modalButtons}>
              <button onClick={confirmhandledelete}>Yes</button>
              <button onClick={() => setshowdelete(false)}>No</button>
            </div>
          </div>
        </div>
      )}
      {showupdate && <Update1 id={id} setshowupdate={setshowupdate} />}
      <br /><br />
       <h2 style={{textAlign:"center"}}>Registered Users</h2>
      <div style={{ display: "flex", justifyContent: "center", marginTop: 60 }}>
        <TableContainer component={Paper} sx={{ width: 1100 }}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell sx={{ fontSize: 18, fontWeight: 800 }} align="left">
                  SNo.
                </TableCell>
                <TableCell sx={{ fontSize: 18, fontWeight: 800 }} align="left">
                  Name
                </TableCell>
                <TableCell sx={{ fontSize: 18, fontWeight: 800 }} align="left">
                  Email
                </TableCell>
                <TableCell sx={{ fontSize: 18, fontWeight: 800 }} align="left">
                  Password
                </TableCell>
                <TableCell sx={{ fontSize: 18, fontWeight: 800 }} align="left">
                  Actions
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {rusers &&
                rusers.map((element: any,index:any) => (
                  <TableRow key={element._id}>
                    <TableCell sx={{ fontWeight: 800 }}>{index+1}.</TableCell>
                    <TableCell>{element.name}</TableCell>
                    <TableCell>{element.email}</TableCell>
                    <TableCell>{element.password}</TableCell>
                    <TableCell sx={{ display: "flex", gap: 2 }} align="left">
                      <button
                        className={edit.edit}
                        onClick={() => {
                          setshowupdate(true);
                          setId(element._id);
                        }}
                      >
                        Edit <i className="fa-solid fa-pen-to-square"></i>
                      </button>

                      <button
                        className={styles.delete}
                        onClick={() => handledelete(element._id,element.name)}
                      >
                        Delete <i className="fa-solid fa-trash"></i>
                      </button>
                    </TableCell>
                  </TableRow>
                ))}
            </TableBody>
          </Table>
        </TableContainer>
      </div><br /><br />
      <button
        onClick={goback}
        style={{
          padding: "12px",
          fontSize: "13px",
          fontWeight:"bold",
          backgroundColor: "black",
          color: "white",
          border: "none",
          borderRadius: "100px",
          marginLeft:"242px"
        }}
      >
        Back to prev page
      </button>
    </>
  );
};

export default allregister;
