// Next imports
import type { NextPage } from 'next'
import Head from 'next/head'

// Components imports
import Navbar from '../Components/Navbar'
import Signup from './Signup'


const Home: NextPage = () => {
 
  return (
    <div className='lighttheme'>
      <Head>
        <title>Crud App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Signup/>
     {/* <Allpost/> */}

   
  
    </div>
  )
}

export default Home
