import type { NextPage } from 'next'
import Head from 'next/head'


import Navbar from '../Components/Navbar'
import Allpost from './allpost'
import { useEffect, useState } from 'react'
import Signup from './Signup'


const Home: NextPage = () => {
 
  return (
    <div className='lighttheme'>
      <Head>
        <title>Crud App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Signup/>
     {/* <Allpost/> */}

   
  
    </div>
  )
}

export default Home
