// Next imports
import React, {  useEffect, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";
// Mui imports
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
// Components imports

// Formik and Yup imports
import { Formik, Form, Field, ErrorMessage } from "formik";
import * as Yup from "yup";
// Styles imports
import styles from "../styles/error.module.css";
// Redux imports
import { useDispatch } from "react-redux";
import { loginuser } from "../Features/demo";
import { AppDispatch } from "../store";
// Aos imports
import Aos from "aos";

interface LoginCredentials {
  email: string;
  password: string;
}
const validateschema = Yup.object().shape({
  email: Yup.string().email("Invalid email").required("Email is Required"),
  password: Yup.string().required("Password is Required"),
});

const Login = () => {
  useEffect(() => {
    Aos.init();
  }, []);
  const [username, setusername] = useState("");
  const dispatch: AppDispatch = useDispatch();
  const router = useRouter();

  const handlelogin = async (Loginvalues: LoginCredentials) => {
    try {
      const response = await dispatch(loginuser(Loginvalues));

      // Check if login was successful
      const user = response.payload;
      console.log("payload", user);

      if (user) {
        // Store user information in local storage
        localStorage.setItem("user", JSON.stringify({ Loginvalues, user }));
        // localStorage.setItem("email", Loginvalues.email);
        // localStorage.setItem("password", Loginvalues.password);

        router.push("/Landing");
      } else {
        alert("Invalid username or password");
      }
    } catch (error) {
      alert("An error occurred during login");
    }
  };

  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style>
        {`
  
 
  
  
  
  `}
      </style>

      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
        }}
      >
        <div className="login" data-aos="zoom-in-up" data-aos-duration="1000">
          <Box
            sx={{
              width: "500px",
              padding: 12,
              height: "300px",
            }}
          >
            <Formik
              initialValues={{ email: "", password: "" }}
              validationSchema={validateschema}
              onSubmit={handlelogin}
            >
              <Form>
                <h2>Login</h2>
                <br />
                <Field
                  as={TextField}
                  label="Email"
                  variant="outlined"
                  name="email"
                  type="email"
                  sx={{
                    width: "100%",
                  }}
                  InputProps={{
                    style: {
                      borderRadius: "12px",
                    },
                  }}
                />
                <ErrorMessage
                  name="email"
                  component="div"
                  className={styles.error}
                />
                <br />
                <br />

                <Field
                  as={TextField}
                  label="Password"
                  variant="outlined"
                  name="password"
                  type="password"
                  sx={{
                    width: "100%",
                  }}
                  InputProps={{
                    style: {
                      borderRadius: "12px",
                    },
                  }}
                />
                <ErrorMessage
                  name="password"
                  component="div"
                  className={styles.error}
                />
                <br />
                <br />

                <Stack spacing={2} direction="column">
                  <Button variant="contained" type="submit">
                    Submit
                  </Button>
                  <h5>
                    <Link
                      href="/Signup"
                      style={{
                        color: "dodgerblue",
                        textDecoration: "underline",
                      }}
                    >
                      Don&apos;t Have an Account?
                    </Link>
                  </h5>
                </Stack>
              </Form>
            </Formik>
          </Box>
        </div>
      </Box>
    </>
  );
};

export default Login;
