import * as React from "react";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Navbar1 from "../Components/Navbar1";
import { useSelector, useDispatch } from "react-redux";
import Rating from "@mui/material/Rating";
import { useState } from "react";
import { Badge, Stack } from "@mui/material";
import Description from "../Components/Description";
import { addtocart, addtowishlist } from "../Features/productsslice";
import Head from "next/head";
import Aos from "aos";
import { useRef } from "react";
import styles from "../styles/confirm.module.css";
import { useRouter } from "next/router";

const Products = () => {
  const router = useRouter();
  const items = useSelector((state: any) => state.allcarts.items);

  const [id, setId] = useState();
  const [visibleItems, setVisibleItems] = useState(4);
  const [full, setfull] = useState(false);
  const [alreadyAdded, setalreadyAdded] = useState(false);
  const [showdescription, setshowdescription] = useState(false);
  const [alreadywishlist, setalreadywishlist] = useState(false);
  const [showwish, setshowwish] = useState(false);

  const dispatch = useDispatch();
  const { cart, wishlist } = useSelector((state: any) => state.allcarts);

  const loadMoreButtonRef = React.useRef<HTMLInputElement>(null);
  const [showpopup, setshowpopup] = useState(false);
  React.useEffect(() => {
    Aos.init({ duration: 800 });
  }, [visibleItems]);


  const handleLoadMore = () => {
    setVisibleItems((prevVisibleItems) => prevVisibleItems + 4);
    setTimeout(() => {
      if (loadMoreButtonRef.current) {
        loadMoreButtonRef.current.scrollIntoView({
          behavior: "smooth",
          block: "end",
          inline: "nearest",
        });
      }
    }, 100);
  };
  const handleaddtocart = (values: any) => {
    const existingItem = cart.find((item: any) => item.id === values.id);

    if (existingItem) {
      setalreadyAdded(true);
      return;
    }
    if (cart.length >= 5) {
      setfull(true);
      return;
    }

    dispatch(addtocart(values));
    console.log("carts", values);
    setshowpopup(true);
    setTimeout(() => {
      setshowpopup(false);
    }, 1000);
  };
  const handleaddtowish = (wish: any) => {
    const existing = wishlist.find((item: any) => item.id === wish.id);
    if (existing) {
      setalreadywishlist(true);
      return;
    }
    dispatch(addtowishlist(wish));
    setshowwish(true);
    setTimeout(() => {
      setshowwish(false);
    }, 1000);
  };
  const seewishlist = () => {
    router.push("/Wishlist");
  };

  return (
    <>
      <style>
        {`
      
      .popup {
        position: fixed;
        top: 10%;
        left: 50%;
        transform: translateX(-50%);
        background-image: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));
        padding: 22px;
        border-radius: 4px;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
        z-index: 9999;
      }
      
       p{
        margin: 0;
        font-size: 22px;
        font-weight: 500;
        color:white;
      }
      fa-heart.active{
        background-color: red;
      }
      
      
      
      `}
      </style>

      <Head>
        <title>Products Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </Head>
      {showdescription && (
        <Description setshowdescription={setshowdescription} id={id} />
      )}
      <Navbar1 />
      <br />

      {showpopup && (
        <div className="popup">
          <p>Item has been added to Cart</p>
        </div>
      )}
      {full && (
        <div className={styles.prompt}>
          <p className={styles.message}>Can't exceed more then 5 items !!!</p>
          <button className={styles.okButton} onClick={() => setfull(false)}>
            OK
          </button>
        </div>
      )}
      {alreadyAdded && (
        <div className={styles.prompt}>
          <p className={styles.message}>Item is already in cart!!!</p>
          <button
            className={styles.okButton}
            onClick={() => setalreadyAdded(false)}
          >
            OK
          </button>
        </div>
      )}
      {alreadywishlist && (
        <div className={styles.prompt}>
          <p className={styles.message}>Item is already in your wishlist!!!</p>
          <button
            className={styles.okButton}
            onClick={() => setalreadywishlist(false)}
          >
            OK
          </button>
        </div>
      )}
      {showwish && (
        <div className="popup">
          <p>Item has been added to Wishlist</p>
        </div>
      )}
      <Button
        variant="text"
        size="large"
        style={{ position:"fixed",right:"10px"}}
        onClick={seewishlist}
      >
             <Badge
       badgeContent={wishlist.length}
       anchorOrigin={{
         vertical: "top",
         horizontal: "right",
       }}
       sx={{fontSize:22}}
       >
        <span style={{fontSize:"30px"}}>&#10084;</span>
      
       </Badge>
      </Button>
      <br />
      <br />
      <Container
        maxWidth="xl"
        sx={{
          display: "flex",
          flexDirection: "row",
          flexWrap: "wrap",
          gap: "10px",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        {items.slice(0, visibleItems).map((item: any) => (
          <Card
            sx={{ height: 540, width: 320 }}
            key={item.id}
            data-aos="fade-up"
            className="card"
          >
            <CardMedia
              sx={{ height: 300, width: 320 }}
              image={item.img}
              title={item.title}
            />
            <CardContent>
              <Typography gutterBottom variant="h6" component="div">
              {item.title.length > 30 ? `${item.description.slice(0,20 )}...` : item.title}
              </Typography>
              <Typography variant="body2" color="text.secondary">
              {item.description.length > 50 ? `${item.description.slice(0,50 )}...` : item.description}
              </Typography>
              <Typography variant="h6" color="text.secondary">
                ₹ {item.price}
              </Typography>
              <Rating name="read-only" value={item.rating} readOnly />
            </CardContent>
            <CardActions>
              <Stack spacing={2} direction="row">
                <Button size="small" variant="contained">
                  Buy
                </Button>
                <Button
                  size="small"
                  onClick={() => handleaddtocart(item)}
                  variant="contained"
                >
                 <i className="fa-solid fa-cart-shopping"></i>
                </Button>
                <Button
                  size="small"
                  variant="outlined"
                  onClick={() => handleaddtowish(item)}
                >
                  &#10084;
                </Button>
                
              </Stack>
              <Stack spacing={2} direction="row">
              <Button
                  size="small"
                  variant="outlined"
                  onClick={() => {
                    setshowdescription(true);
                    setId(item.id);
                  }}
                >
                  Details
                </Button>
              </Stack>
            </CardActions>
          </Card>
        ))}
      </Container>
      <br />

      <div ref={loadMoreButtonRef}></div>
      {visibleItems < items.length && (
        <div style={{ display: "flex", justifyContent: "center" }}>
          <Button variant="contained" onClick={handleLoadMore}>
            Load More Items
          </Button>
        </div>
      )}
    </>
  );
};

export default Products;
